apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xilian.fullname" . }}
  namespace: {{ include "xilian.namespace" . }}
  labels:
    {{- include "xilian.labels" . | nindent 4 }}
automountServiceAccountToken: false
